version: '3.7'

services:
  bravodb1:
    container_name: bravodb1
    image: bravo/bravodb:0.1
    environment:
      - bravodb.discovery.server.self.host=bravodb1
      - bravodb.discovery.server.self.port=8919
      - bravodb.discovery.server.other.host=bravodb2
      - bravodb.discovery.server.other.port=8919
    networks:
      - bravo-network

  bravodb2:
    container_name: bravodb2
    image: bravo/bravodb:0.1
    environment:
      - bravodb.discovery.server.self.host=bravodb2
      - bravodb.discovery.server.self.port=8919
      - bravodb.discovery.server.other.host=bravodb1
      - bravodb.discovery.server.other.port=8919
    networks:
      - bravo-network


networks:
  bravo-network: